# Generated by Django 4.0.5 on 2022-07-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=20)),
                ('image_cat', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_couleur', models.CharField(max_length=20)),
                ('caractere_coluleur', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_reduc', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('promotion', models.BooleanField(default=False)),
                ('reduction', models.BooleanField(default=False)),
                ('etat', models.CharField(blank=True, choices=[('', ''), ('New', 'new'), ('Sale', 'sale')], default=None, max_length=255, null=True)),
                ('currencies', models.CharField(choices=[('XOF', 'Xof'), ('€', 'euro'), ('$', 'dollar')], max_length=255)),
                ('taille', models.CharField(blank=True, choices=[('S', 'tres_petit'), ('M', 'petit'), ('L', 'moyen'), ('XL', 'grand'), ('XXL', 'tres_grand')], default=None, max_length=255, null=True)),
                ('collections', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_cate', to='Shop.categorie')),
                ('couleur', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Shop.couleur')),
                ('valeur_reduction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.reduction')),
            ],
        ),
    ]
