# Generated by Django 4.0.5 on 2022-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduction',
            name='nom_reduction',
            field=models.IntegerField(),
        ),
    ]
