# Generated by Django 4.0.5 on 2022-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='collections',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='etat',
            field=models.CharField(blank=True, choices=[('', ''), ('News', 'news'), ('Sale', 'sale')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='taille',
            field=models.CharField(blank=True, choices=[('S', 'tres_petit'), ('M', 'petit'), ('L', 'moyen'), ('XL', 'grand'), ('XXL', 'tres_grand')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='valeur_reduction',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
