# Generated by Django 4.0.5 on 2022-07-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_categorieimages_articles_autre_image_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutresImagesArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image1', models.FileField(blank=True, default=None, null=True, upload_to='cat_image1')),
                ('cat_image2', models.FileField(blank=True, default=None, null=True, upload_to='cat_image2')),
                ('cat_image3', models.FileField(blank=True, default=None, null=True, upload_to='cat_image3')),
                ('cat_image4', models.FileField(blank=True, default=None, null=True, upload_to='cat_image4')),
                ('cat_image5', models.FileField(blank=True, default=None, null=True, upload_to='cat_image5')),
                ('cat_image6', models.FileField(blank=True, default=None, null=True, upload_to='cat_image6')),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='autre_image_article',
        ),
        migrations.DeleteModel(
            name='CategorieImages',
        ),
        migrations.AddField(
            model_name='autresimagesarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_article', to='Shop.articles'),
        ),
    ]
