# Generated by Django 4.0.5 on 2022-06-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_articles_valeur_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='valeur_reduction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.reduction'),
            preserve_default=False,
        ),
    ]
