# Generated by Django 4.0.5 on 2022-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_articles_collections_alter_articles_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduction',
            name='valeur_reduc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
