# Generated by Django 4.0.5 on 2022-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_article_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reduction',
            old_name='nom_reduction',
            new_name='nom_reduc',
        ),
        migrations.RemoveField(
            model_name='article',
            name='symbole',
        ),
        migrations.AddField(
            model_name='article',
            name='collections',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='currencies',
            field=models.CharField(choices=[('XOF', 'Xof'), ('€', 'euro'), ('$', 'dollar')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='valeur_reduction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='image_cat',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reduction',
            name='valeur_reduc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='reduction',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Symbole',
        ),
    ]
