# Generated by Django 4.0.5 on 2022-06-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_reduction_valeur_reduc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduction',
            name='nom_reduc',
        ),
    ]
