# Generated by Django 4.0.5 on 2022-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_articles_prix_reduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='reduction',
            field=models.BooleanField(default=False),
        ),
    ]
