# Generated by Django 4.0.5 on 2022-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_articles_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='etat',
            field=models.CharField(blank=True, choices=[('', ''), ('New', 'new'), ('Sale', 'sale')], default=None, max_length=255, null=True),
        ),
    ]
