# Generated by Django 4.0.5 on 2022-06-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='reseau_social_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseau_social', to='SiteWeb.reseausocial'),
        ),
    ]
